https://docs.scipy.org/doc/numpy-dev/user/quickstart.html 
核心就是numpy.ndarray 这个同质多维数组


In [28]:
import numpy as np

In [30]:
#Array Creation
a = np.array([2,3,4])
b = np.arange(15)
c = np.arange(1,10,1).reshape(3,3)
d = np.zeros(12).reshape(3,4)

In [31]:
#Attributes
print c.shape
print c.dtype
print type(c)
print c

(3L, 3L)
int32
<type 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
#Basic Operations
print a**3 #乘方
print a*a #对应元素相乘
print a.dot(a.T) #矩阵乘法
print a+a
print a>3
print np.exp(a)


print c
print c.sum(axis=0)  #axis=0,是指列这个轴
print c.sum(axis=1)
print c.max(axis=0)

[ 8 27 64]
[ 4  9 16]
29
[4 6 8]
[False False  True]
[  7.3890561   20.08553692  54.59815003]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[7 8 9]


In [33]:
#Indexing, Slicing and Stacking together
print a[1:3]
print np.vstack((a,a)) #沿axis=0，何并
print np.hstack((a,a)) #沿axis=1，何并
b=np.vstack((a,a))
print b[0,:]

print a[a>3] #Indexing with Boolean Arrays

[3 4]
[[2 3 4]
 [2 3 4]]
[2 3 4 2 3 4]
[2 3 4]
[4]


In [34]:
#Broadcasting  
#    Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape.
print a
print c
print a*3
print c+a

[2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6  9 12]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [37]:
#Linear Algebra
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print a
print a.dot(a)
print a.T
print np.linalg.inv(a)
print np.linalg.eig(a)


[[ 1.  2.]
 [ 3.  4.]]
[[  7.  10.]
 [ 15.  22.]]
[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [42]:
a = np.array([2,3,4])
print a[1]
b=a.T
print a
print b

3
[2 3 4]
[2 3 4]
